package com.mec.volunteer.model;

public interface IErrorMessage {
	String SUCCESS_NUMBER = "000000";
	String SUCCESS_MESSAGE = "登录成功";
	
	String FAILURE_NORMAL_USER_NOT_EXIST_NUMBER = "000001";
	String FAILURE_NORMAL_USER_NOT_EXIST_MESSAGE = "账号不存在！";

	String FAILURE_NORMAL_PASSWORD_NOT_RIGHT_NUMBER = "000002";
	String FAILURE_NORMAL_PASSWORD_NOT_RIGHT_MESSAGE = "密码不正确！";

	String FAILURE_NORMAL_USER_ID_NOT_RIGHT_NUMBER = "000003";
	String FAILURE_NORMAL_USER_ID_NOT_RIGHT_MESSAGE = "账号不正确！";
	
	String FAILURE_NORMAL_PASSWORD_SAME_NUMBER = "000004";
	String FAILURE_NORMAL_PASSWORD_SAME_MESSAGE = "新旧密码相同！";
}
